import styles from '../home.module.css';

export function AboutSection() {
  return (
    <section id="about">
      <div className="section-label">// Why We&apos;re Different</div>
      <h2 className="section-title">Built by the Operator Dataminr Doesn&apos;t Have</h2>

      <div className={styles.credContent}>
        <div className={styles.credStats}>
          <div className={styles.credStat}>
            <div className="value">25+</div>
            <div className="label">Years in security, technology &amp; intelligence</div>
          </div>
          <div className={styles.credStat}>
            <div className="value">20+</div>
            <div className="label">Years operating in Latin America</div>
          </div>
          <div className={styles.credStat}>
            <div className="value">5,000+</div>
            <div className="label">Personnel managed, $100M+ budgets</div>
          </div>
        </div>
        <div className={styles.credText}>
          <p>
            <strong>Chris Dover — Founder &amp; CEO, Centinela AI</strong>
          </p>
          <p>
            US Marine Veteran. Department of State High Threat Protection.
            Control Risks Group. Triple Canopy. 20+ years on the ground across
            Latin America — not analyzing it from a desk in New York.
          </p>
          <p>
            That&apos;s the difference between Centinela and a $200K enterprise platform.
            Dataminr has AI engineers. We have AI engineers <strong>and</strong> an operator
            who&apos;s run executive protection programs, coordinated with intelligence
            agencies, and managed security operations across the most dangerous
            corridors in the hemisphere. The analysis isn&apos;t generated by an algorithm
            that read some Reuters articles — it&apos;s informed by decades of ground truth.
          </p>
          <p>
            Now backed by owned GPU infrastructure and private AI, we
            deliver the intelligence we always wanted — at machine speed, with
            operator judgment, at 1/10th the price of the incumbents.
          </p>
          <p>
            Centinela AI is a service of <strong>Enfocado Capital LLC</strong>.
          </p>
        </div>
      </div>
    </section>
  );
}
